### ISSUE TITLE
No sound on call

### ISSUE THREAD

**Issue by phani-learner** [mitwo-dev/proprietary_vendor_xiaomi#1]
My phone is Mi2s - 32gb
When i call i can't hear any sound (other person can't hear me i can't hear other person loud speaker also won't work) weired problem
At every other place sound is perfect

In earlier builds it worked i mean when there was a screen tearing issue and camera not connecting problem
Now i'm facing this problem
Can someone look into it??
Both CM 10.1 and CM 10.2 its not working
By the way its working in MIUI
Tried installing in system1 / system2 formatted everything etc etc after all attempts and testing with previous build i'm posting here

**Comment by ivan19871002** [comment]
https://github.com/mitwo-dev/android_device_xiaomi_aries/issues/17
