### ISSUE TITLE
Use opensource power HAL

### ISSUE THREAD

**Issue by M1cha** [mitwo-dev/proprietary_vendor_xiaomi#2]
we should use the QCOM power HAL from https://github.com/CyanogenMod/android_device_qcom_common/tree/cm-12.1/power

and examine the existing binary to find code we may need to reverse engineer.

**Comment by ivan19871002** [comment]
https://github.com/mitwo-dev/proprietary_vendor_xiaomi/commit/06843f5312f15258449fd00b80afabc7399ad42f
